### ISSUE TITLE
Other Sensors

### ISSUE THREAD

**Issue by bretsky84** [johnwargo/pi_weather_station#3]
Is it possible to add other sensors to the python config?  If so, is it documented anywhere?

**Comment by johnwargo** [comment]
Sure, you can do whatever you want.  It’s open source code, just add your sensors and write the code to read them and upload the data.  No, it’s not documented as this project does everything I needed it to do.

**Comment by johnwargo** [comment]
@bretsky84 I apologize for my earlier short and flippant response, I was on vacation and in a hurry. 

So the project was built using an add-on board that contains enough sensors to make the project a useful weather station. If you want to add more sensors, you'll just need to wire them in to the GPIO connector on the Raspberry Pi, then add the code you need to read the sensor(s) and store and display the data somewhere. I didn't need to make accommodations for any additional sensors as I simply didn't need them.

Depending on the sensor you add, you may or may not be able to store it in Weather Underground as they may not have built in support for that measurement into their system. 

Is any of that documented? No, of course not.
