### ISSUE TITLE
Pi Weather Station Problem

### ISSUE THREAD

**Issue by n6egy** [johnwargo/pi_weather_station#5]
In running pi_weather_station I receive the following debug note: 

Python 3.7.3 (/usr/bin/python3)
>>> %cd /home/pi/pi_weather_station
>>> %Run weather_station.py
Traceback (most recent call last):
  File "/home/pi/pi_weather_station/weather_station.py", line 17, in <module>
    from urllib import urlencode
ImportError: cannot import name 'urlencode' from 'urllib' (/usr/lib/python3.7/urllib/__init__.py)
>>> 
Using an RPi 4, RPi AstroPi Sense hat, current upgrade of Raspbian Buster and Python 3.7.

Any ideas where "urlencode" resides so it can be imported?

**Comment by n6egy** [comment]
Installed a new Raspbian image and pi_weather_station.  Works fine.  Have no idea why not working before but problem now solved.

**Comment by johnwargo** [comment]
@n6egy glad it worked out for you. I've had three or four people reach out to me with weird errors and I think it's mostly because of installation issues. Enjoy the weather station.
